# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:13
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('blog', '0003_auto_20160223_1558'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('published_posts', blog.models.PublishedPostForSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
