# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160226_1613'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
            ],
        ),
    ]
