# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160226_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='disqus_identifier',
            field=models.CharField(blank=True, help_text="This shouldn't need to be changed", max_length=255),
        ),
    ]
