# Generated by Django 2.1.5 on 2019-03-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190228_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
    ]
