# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='sites',
            new_name='site',
        ),
    ]
